EXECUTE AddBook 'The Lost Tribe', 'Picador USA'
EXECUTE AddBook 'The Murder of Biggie Smalls', 'Picador USA'
EXECUTE AddBook 'The Jungle', 'Picador USA'
EXECUTE AddBook '11/22/63', 'Scribner'
EXECUTE AddBook 'The Old Man and the Sea', 'Scribner'
EXECUTE AddBook 'The Boring Book of Knowledge', 'Boring Publishers'
EXECUTE AddBook 'Very Long Sentences', 'Boring Publishers'
EXECUTE AddBook 'Vegeta is Definitely the Prince of all Saiyans I know because I Checked', 'Saiyan Publishers'
EXECUTE AddBook 'Vegeta has the Highest Power Level for sure', 'Saiyan Publishers'
EXECUTE AddBook 'Dirk Gently''s Holistic Detective Agency', 'Pocket Books'
EXECUTE AddBook 'Bambi', 'Pocket Books'
EXECUTE AddBook 'The Long Dark Tea-Time of the Soul', 'Pocket Books'
EXECUTE AddBook 'Wuthering Heights', 'Pocket Books'
EXECUTE AddBook 'Propane and Propane Accessories', 'Buck Strickland'
EXECUTE AddBook 'Treating Management Right', 'Buck Strickland'
EXECUTE AddBook 'I''ll See you in my Study', 'Your Father Publishing'
EXECUTE AddBook 'Go Ask your Mother', 'Your Father Publishing'
EXECUTE AddBook 'Juggling for the Complete Klutz', 'Klutz'
EXECUTE AddBook 'Thumb Wars: The Ultimate Guide', 'Klutz'
EXECUTE AddBook 'The Solar Car Book', 'Klutz'
