EXECUTE AddAuthor '1', 'Mark Lee'
EXECUTE AddAuthor '2', 'Cathy Scott'
EXECUTE AddAuthor '3', 'Upton Sinclair'
EXECUTE AddAuthor '4', 'Stephen King'
EXECUTE AddAuthor '5', 'Ernest Hemmingway'
EXECUTE AddAuthor '6', 'Cactaur'
EXECUTE AddAuthor '7', 'Tonberry'
EXECUTE AddAuthor '8', 'Vegeta'
EXECUTE AddAuthor '9', 'Vegeta'
EXECUTE AddAuthor '10', 'Douglas Adams'
EXECUTE AddAuthor '11', 'Felix Salten'
EXECUTE AddAuthor '12', 'Douglas Adams'
EXECUTE AddAuthor '13', 'Emily Bronte'
EXECUTE AddAuthor '14', 'Hank Hill'
EXECUTE AddAuthor '15', 'Buck Strickland'
EXECUTE AddAuthor '16', 'Clay Puppington'
EXECUTE AddAuthor '17', 'Clay Puppington'
EXECUTE AddAuthor '18', 'Anonymous'
EXECUTE AddAuthor '19', 'Biff Strongman'
EXECUTE AddAuthor '20', 'Anonymous'
